config/routes.rb
RailsAdmin::Engine.routes.draw do
  resources :interventions
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  scope protocol: 'https://', constraints: {protocol: 'https://'} do
    resources :radmin
  end

  get "polly", to: "rails_admin.polly_path"
end

Rails.application.routes.draw do
  resources :interventions
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  # get 'errors/not_found'
  # get 'errors/internal_server_error~'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  #  :controllers => { :sessions => 'sessions' }
  scope '/employee' do
    resources :users
  end
  root to: 'pages#index'
  get "residential", to: "pages#residential"
  get "commercial", to: "pages#commercial"
  get "quote", to: "quotes#new"
  get "index", to: "pages#index"
  post "lead", to: "lead#create"
  get "login", to: "pages#login"
  get 'users/:id' => 'users#show'
  # get "gmaps", to: 'rails_admin#main#google'
  # get 'google', to: "pages#google"

#   get 'google', to: "pages#google"
  # patch 'elevators/:status', to: "elevator#update"
 # get "portfolio", to: "pages#portfolio"

  resources :quotes

    resources :customers do
      collection do
          get :search
      end
    end

    resources :buildings do
      collection do
          get :search
      end
    end

    resources :batteries do
      collection do
          get :search
      end
    end

    resources :columns do
      collection do
          get :search
      end
    end


    resources :elevators do
      collection do
          get :search
      end
    end

    resources :employee do
      collection do
          get :search
      end
    end
  
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/quote.rb
class Quote < ApplicationRecord
   belongs_to :user
end

app/controllers/quotes_controller.rb
require 'rest_client'
require 'json'

class QuotesController < ApplicationController
    respond_to :js, only: [:create]
    respond_to :html

    def index
        @quotes = Quote.all
    end

    def show
        @quote = Quote.find(params[:id])
    end

    def new
        @quote = Quote.new
    end

    def create
        freshdesk_domain = ENV["BASE_URL"]
        user_name_or_api_key =  ENV["FRESH_KEY"]
        password_or_x = "X"

        building_type = params["building-type"]
        amount_of_floors = params["number-of-floors-input"]
        amount_of_elevators = params["elevator-amount"]
        final_price = params["final-price"]
        elevator_type = params[:product]
        installation_price = params["installation-fees"]

        @quote = Quote.new(quote_params)
        @quote.building_type = building_type
        @quote.amount_of_floors = amount_of_floors
        @quote.amount_of_elevators = amount_of_elevators
        @quote.final_price = final_price
        @quote.elevator_type = elevator_type
        @quote.installation_price = installation_price

        if user_signed_in?
            @quote.user_id = current_user.id
            @quote.save!
        
                if @quote.save
                    redirect_back fallback_location: new_quote_path, notice: "Quote has been sent successfully !"

                    quote_payload =  {
                        status: 2,
                        priority: 2,
                        type: "Feature Request",
                        email: @quote.user.email,
                        subject: "new quote request from #{@quote.user.company_name} #{Time.now}",
                        description: "#{@quote.user.company_name} has requested #{@quote.amount_of_elevators} elevators for a #{@quote.building_type} type of building with #{@quote.amount_of_floors} floors. <br/>
                        The client chose #{@quote.elevator_type} product type. After installation fees #{@quote.installation_price}, the final prise is #{@quote.final_price}. <br/>
                        Contact email #{@quote.user.email}"
                    }

                    freshdesk_api_path = 'api/v2/tickets'
                    freshdesk_api_url  = "https://codeboxx4015.freshdesk.com/#{freshdesk_api_path}"

                    site = RestClient::Resource.new(freshdesk_api_url, user_name_or_api_key, password_or_x)
 
                    begin
                        response = site.post(quote_payload.to_json, {content_type: :json, accept: :json})
                        # RestClient.post freshdesk_api_url, multipart_payload.to_json, {content_type: :json, accept: :json}
                        puts "response_code: #{response.code} \nLocation Header: #{response.headers[:Location]} \nresponse_body: #{response.body} \n"
                    rescue RestClient::Exception => exception
                        puts 'API Error: Your request is not successful. If you are not able to debug this error properly, mail us at support@freshdesk.com with the follwing X-Request-Id'
                        puts "X-Request-Id : #{exception.response.headers[:x_request_id]}"
                        puts "Response Code: #{exception.response.code} \nResponse Body: #{exception.response.body} \n"
                    end
                    
                else
                    redirect_back fallback_location: root_path, notice: "Please sign up or sign in before submitting a quote!"
            
                respond_with(@qoute)
                end
        end   
    end



    private
        def quote_params
            params.fetch(:quote, {})
        end

end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/index.html.erb
<h1>Listing Quotes</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @quotes.each do |quote| %>
    <tr>
      <td><%= quote.title %></td>
      <td><%= quote.text %></td>
      <td><%= link_to 'Show', quote_path(quote) %></td>
    </tr>
  <% end %>
</table>

app/views/quotes/new.html.erb
<%= form_with scope: :quote, url: quotes_path, local: true, :html => {:format => "js"} do |form| %>

<section>
    <div class="container">
        <div class="blog-post-item">
            <h1>Request a Quote:</h1>
            <form id="myForm" enctype="multipart/form-data">

                
                <fieldset>
                    <!-- <input type="hidden" name="action" value="contact_send" /> -->
                    <div class="row">
                    
                        <div class="col-md-12">
                            <label for="building-type">Building Type</label>
                            <select class="form-control pointer" name="building-type" id="building-type" style="font-size:100%">
                                            <option value="">---Select---</option>
                                            <option  id="residential" value="residential" >Residential</option>
                                            <option  id="commercial" value="commercial">Commercial</option>
                                            <option  id="corporate" value="corporate">Corporate</option>
                                            <option  id="hybrid" value="hybrid">Hybrid</option>
                            </select>
                        </div>
                    </div>


                    <!--1-->
                    <div class="col-md-4" id="number-of-apartments" style="display:none">
                        <label for="number-of-apartments-input" >The number of apartments <br/> in the building</label>
                        <input  type="number" min="0" value="" class="form-control" name="number-of-apartments-input" id="number-of-apartments-input" style="font-size:100%">
                    </div>
                    <!--2-->
                    <div class="col-md-4" id="number-of-floors" style="display:none">
                        <label for="number-of-floors-input">The number of floors contained in the building, excluding basements</label>
                        <input  type="number" min="0" value="" class="form-control" name="number-of-floors-input" id="number-of-floors-input" style="font-size:100%">
                    </div>
                    <!--3-->
                    <div class="col-md-4" id="number-of-basements" style="display:none">
                        <label for="number-of-basements-input">The number of basements contained in the building</label>
                        <input  type="number" min="0" value="" class="form-control" name="number-of-basements-input" id="number-of-basements-input" style="font-size:100%">
                    </div>

                    <!--4-->
                    <div class="col-md-4" id="number-of-companies" style="display:none">
                        <label for="number-of-companies-iput">The number of <br/> distinct businesses.</label>
                        <input  type="number" min="0" value="" class="form-control" name="number-of-companies-iput" id="number-of-companies-iput" style="font-size:100%">
                    </div>

                    <!--5-->
                    <div class="col-md-6" id="number-of-parking-spots" style="display:none">
                        <label for="number-of-parking-spot-input">The number of parking space <br> available</label>
                        <input  type="number" min="0" value="" class="form-control" name="number-of-parking-spots-input" id="number-of-parking-spot-input" style="font-size:100%">
                    </div>

                    <!--6-->
                    <div class="col-md-4" id="number-of-elevators" style="display:none">
                        <label for="number-of-elevators-input">The number of elevator cages <br> to be deployed</label>
                        <input  type="number" min="0" value="" class="form-control" name="number-of-elevators-input" id="number-of-elevators-input" style="font-size:100%">
                    </div>

                    <!--7-->
                    <div class="col-md-3" id="number-of-corporations" style="display:none">
                        <label for="number-of-corporations-input">The number of separate tenant companies</label>
                        <input  type="number" min="0" value="" class="form-control" name="number-of-corporations-input" id="number-of-corporations-input" style="font-size:100%">
                    </div>

                    <!--8-->
                    <div class="col-md-3" id="maximum-occupancy" style="display:none">
                        <label for="maximum-occupancy-input">The maximum number of occupants per floor</label>
                        <input  type="number" min="0" value="" class="form-control" name="maximum-occupancy-input" id="maximum-occupancy-input" style="font-size:100%">
                    </div>

                    <!--9-->
                    <div class="col-md-4" id="business-hours" style="display:none">
                        <label for="business-hours-input">The number of hours of activity of the building (the maximum being 24)</label>
                        <input  type="number" min="0" max="24" value="" class="form-control" name="business-hours-input" id="business-hours-input" style="font-size:100%">
                    </div>


                </fieldset>
            </form>


        </div>


        <div class="btn-group-lg" role="group" id="products" aria-label="Basic radio toggle button group" style="position:relative; left:300px">
            <input type="radio" class="btn-check" name="product" value="standard" id="standard">
            <label class="btn btn-outline-danger" for="standard">Standard</label> &nbsp;

            <input type="radio" class="btn-check" name="product" value="premium" id="premium">
            <label class="btn btn-outline-danger" for="premium">Premium</label> &nbsp;

            <input type="radio" class="btn-check" name="product" value="excelium" id="excelium">
            <label class="btn btn-outline-danger" for="excelium">Excelium</label>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-3">
                <label for="elevator-amount">N. of Elevators needed</label>
                <input type="text" class="" name="elevator-amount" id="elevator-amount" style="font-size:100%" readonly>
            </div>

            <div class="col-md-3">
                <label for="elevator-unit-price">The unit price of each elevator</label>
                <input type="text" class="" name="elevator-unit-price" id="elevator-unit-price" style="font-size:100%" readonly>
            </div>
            <div class="col-md-3">
                <label for="elevator-total-price">The total price of the elevators</label>
                <input type="text" class="" name="elevator-total-price" id="elevator-total-price" style="font-size:100%" readonly>
            </div>
            <div class="col-md-3">
                <label for="installation-fees">The installation fees</label>
                <input type="text" class="" name="installation-fees" id="installation-fees" style="font-size:100%" readonly>
            </div>
        </div>
        <hr>
        <div class="row" style="justify-content: center">
            <div class="col-md-4">
                <label for="final-price"><strong>The final price</strong></label>
                <input type="text" class="" name="final-price" id="final-price" style="font-size:100%" readonly>
            </div>
            
        </div>
        <br><div class="row" style="justify-content: center">
            <div class="col-md-3">
                 <%= form.submit %>
            </div>
        </div>
    </div>
</section>

 
<% end %>