config/routes.rb
RailsAdmin::Engine.routes.draw do
  resources :interventions
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  scope protocol: 'https://', constraints: {protocol: 'https://'} do
    resources :radmin
  end

  get "polly", to: "rails_admin.polly_path"
end

Rails.application.routes.draw do
  resources :interventions
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  # get 'errors/not_found'
  # get 'errors/internal_server_error~'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  #  :controllers => { :sessions => 'sessions' }
  scope '/employee' do
    resources :users
  end
  root to: 'pages#index'
  get "residential", to: "pages#residential"
  get "commercial", to: "pages#commercial"
  get "quote", to: "quotes#new"
  get "index", to: "pages#index"
  post "lead", to: "lead#create"
  get "login", to: "pages#login"
  get 'users/:id' => 'users#show'
  # get "gmaps", to: 'rails_admin#main#google'
  # get 'google', to: "pages#google"

#   get 'google', to: "pages#google"
  # patch 'elevators/:status', to: "elevator#update"
 # get "portfolio", to: "pages#portfolio"

  resources :quotes

    resources :customers do
      collection do
          get :search
      end
    end

    resources :buildings do
      collection do
          get :search
      end
    end

    resources :batteries do
      collection do
          get :search
      end
    end

    resources :columns do
      collection do
          get :search
      end
    end


    resources :elevators do
      collection do
          get :search
      end
    end

    resources :employee do
      collection do
          get :search
      end
    end
  
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/intervention.rb
class Intervention < ApplicationRecord
end

app/controllers/interventions_controller.rb
require 'rest_client'
require 'json'



class InterventionsController < ApplicationController
  respond_to :js, only: [:create]
  respond_to :html
  before_action :set_intervention, only: %i[ show edit update destroy ]

  # GET /interventions or /interventions.json
  def index
    @intervention = Intervention.all
  end

  # GET /interventions/1 or /interventions/1.json
  def show
    # @intervention = Intervention.find(params[:id])
  end

  # GET /interventions/new
  def new
    @intervention = Intervention.new
  end

  # def index
  #   @employee = Employee.all
  # end

  # def new
  #   @employee = Employee.new
  # end

  # def new
  #   @customers = Customer.new
  # end

  # def show
  #   @customers = Customer.find(params[:id])
  # end

  # def create
  #   company_name = params[:company_name]
  #   @customers = Customer.new(customer_params)
  #    @customers.company_name = company_name
  # end
 

  # def create
  #   company_name = params[:company_name]
  #   @customers = Customer.new(customer_params)
  #    @customers.company_name = company_name
  # end

  # def new 
  #   company_name = params[:company_name]
  #   @customers = Customer.new(customer_params)
  #     @customers.company_name = company_name
  # end

  # GET /interventions/1/edit
  def edit
  end

  # POST /interventions or /interventions.json
  def create

        freshdesk_domain = ENV["BASE_URL"]
        user_name_or_api_key =  ENV["FRESH_KEY"]
        password_or_x = "X"

        customer_id = params["client"]
        building_id = params["building"]
        battery_id = params["battery"]
        column_id = params["column"]
        elevator_id = params["elevator"]
        report = params["description"]
        created_at = params["created-at"]
        updated_at = params["updated-at"]
        employee_id = params["employee"]

        @intervention = Intervention.new(intervention_params)
          @intervention.author = current_user.id
          @intervention.customer_id = customer_id
          @intervention.building_id = building_id
          @intervention.battery_id = battery_id
          @intervention.column_id = column_id
          @intervention.elevator_id = elevator_id
          @intervention.start_date = nil
          @intervention.end_date = nil
          @intervention.result = "Incomplete"
          @intervention.report = report
          @intervention.status = "pending"
          @intervention.created_at = created_at
          @intervention.updated_at = updated_at
          @intervention.employee_id = employee_id


    # respond_to do |format|
    if user_signed_in?
      @intervention.employee_id = current_user.id
      @intervention.author = current_user.id
      @intervention.save!

      
      

      if @intervention.save
          redirect_back fallback_location: new_intervention_path, notice: "Intervention form has been sent successfully !"

          @customer = Customer.find(customer_id)
          puts @customer

        intervention_payload =  {
          status: 2,
          priority: 1,
          type: "Incident",
          email: @customer.email,
          # email: "bootyboy@gmail.com",   
          subject: "#{@customer.contact_name} from Building #{@customer.company_name} sent an intervention request #{Time.now}",
          description: "#{@customer.contact_name} from #{@customer.company_name} has requested for elevator #{@intervention.elevator_id}, in column #{@intervention.column_id}, with battery #{@intervention.battery_id} to be resolved in building #{@intervention.building_id}.<br/>
                        #{@intervention.employee_id} has been assigned to resolve this incident.<br/>
                        Request description: #{@intervention.report}"
          
          }
          freshdesk_api_path = 'api/v2/tickets'
          freshdesk_api_url  = "https://codeboxx4015.freshdesk.com/#{freshdesk_api_path}"

          site = RestClient::Resource.new(freshdesk_api_url, user_name_or_api_key, password_or_x)
          
          begin
            response = site.post(intervention_payload.to_json, {content_type: :json, accept: :json})
            # RestClient.post freshdesk_api_url, multipart_payload.to_json, {content_type: :json, accept: :json}
            puts "response_code: #{response.code} \nLocation Header: #{response.headers[:Location]} \nresponse_body: #{response.body} \n"
          rescue RestClient::Exception => exception
              puts 'API Error: Your request is not successful. If you are not able to debug this error properly, mail us at support@freshdesk.com with the follwing X-Request-Id'
              puts "X-Request-Id : #{exception.response.headers[:x_request_id]}"
              puts "Response Code: #{exception.response.code} \nResponse Body: #{exception.response.body} \n"
          end
        end
      end
    end

  

  # PATCH/PUT /interventions/1 or /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to intervention_url(@intervention), notice: "Intervention was successfully updated." }
        format.json { render :show, status: :ok, location: @intervention }
      else
      format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1 or /interventions/1.json
  def destroy
    @intervention.destroy

    respond_to do |format|
      format.html { redirect_to interventions_url, notice: "Intervention was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intervention_params
      params.fetch(:intervention, {})
    end

 
  


end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<%= form_with(model: intervention, local: true) do |form| %>
  <% if intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_with scope: :quote, url: interventions_path, local: true, :html => {:format => "js"} do |form| %>

<section>
    <div class="container">
        <div class="blog-post-item">
            <h1>Intervention Request Form:</h1>
            <form id="myForm" enctype="multipart/form-data">

                
                <fieldset>
                    <!-- <input type="hidden" name="action" value="contact_send" /> -->
                    <div id="clients" class="row">
                        
                        <div class="col-md-12">
                            <label for="client">CLIENTS</label>
                            <div id="Clients"></div>
                            <select class="form-control pointer" name="client" id="client" style="font-size:100%">
                                        <option value="">---None---</option>
                            </select>
                        </div>
                    </div>

                    <%# BUILDINGS DROPDOWN %>
                    <div id="buildings" class="row" style="display:none">
                    
                        <div  class="col-md-12">
                            <label for="building">BUILDINGS</label>
                            <select class="form-control pointer" name="building" id="building" style="font-size:100%" >
                                            <option value="">---None---</option>
                            </select>
                        </div>
                    </div>

                    <%# BATTERIES DROPDOWN %>
                    <div id="batteries" class="row" style="display:none">
                    
                        <div  class="col-md-12">
                            <label for="battery">BATTERIES</label>
                            <select class="form-control pointer" name="battery" id="battery" style="font-size:100%">
                                            <option value="">---None---</option>
                            </select>
                        </div>
                    </div>

                    <%# COLUMNS DROPDOWN %>
                    <div id="columns" class="row" style="display:none">
                    
                        <div  class="col-md-12">
                            <label for="column">COLUMNS</label>
                            <select class="form-control pointer" name="column" id="column" style="font-size:100%">
                                            <option value="">---None---</option>
                                            
                            </select>
                        </div>
                    </div>

                    <%# ELEVATORS DROPDOWN %>
                    <div id="elevators" class="row" style="display:none">
                    
                        <div  class="col-md-12">
                            <label for="elevator">ELEVATORS</label>
                            <select class="form-control pointer" name="elevator" id="elevator" style="font-size:100%">
                                            <option value="">---None---</option>
                            </select>
                        </div>
                    </div>

                    <%# EMPLOYEES DROPDOWN %>
                    <div id="employees" class="row" style="display:none">
                    
                        <div class="col-md-12">
                            <label for="employee">EMPLOYEES</label>
                            <select class="form-control pointer" name="employee" id="employee" style="font-size:100%">
                                            <option value="">---None---</option>
                                            <%# <option value="">Mathieu Houde</option>
                                            <option value="">Patrick Thibault</option>
                                            <option value="">Francis Patry-Jessop</option>
                                            <option value="">David Amyot</option>
                                            <option value="">Marie-Ève Goupil</option>
                                            <option value="">François Boivin</option>
                                            <option value="">Timothy Wever</option>
                                            <option value="">Kiril Kleinerman</option>
                                            <option value="">Felicia Hartono</option>
                                            <option value="">Eileen Ai</option> %>

                            </select>
                        </div>
                    </div>

                    <div class="row">
                            <div class="col-md-12">
                                <label for="description">Description *</label>
                                <textarea required maxlength="10000" rows="8" style="font-size:100%" class="form-control" name="description" id="description"></textarea>
                            </div>
                        </div>


        </div>

        <br><div class="row" style="justify-content: center">
            <div class="col-md-3"> 
                 <%= form.submit %>
            </div>
        </div>
    </div>
</section>

 
<% end %>


<%# <%= link_to 'New Intervention', new_intervention_path %> 

app/views/interventions/new.html.erb
<h1>New Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Back', interventions_path %>

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>