config/routes.rb
RailsAdmin::Engine.routes.draw do
  resources :interventions
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  scope protocol: 'https://', constraints: {protocol: 'https://'} do
    resources :radmin
  end

  get "polly", to: "rails_admin.polly_path"
end

Rails.application.routes.draw do
  resources :interventions
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  # get 'errors/not_found'
  # get 'errors/internal_server_error~'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  #  :controllers => { :sessions => 'sessions' }
  scope '/employee' do
    resources :users
  end
  root to: 'pages#index'
  get "residential", to: "pages#residential"
  get "commercial", to: "pages#commercial"
  get "quote", to: "quotes#new"
  get "index", to: "pages#index"
  post "lead", to: "lead#create"
  get "login", to: "pages#login"
  get 'users/:id' => 'users#show'
  # get "gmaps", to: 'rails_admin#main#google'
  # get 'google', to: "pages#google"

#   get 'google', to: "pages#google"
  # patch 'elevators/:status', to: "elevator#update"
 # get "portfolio", to: "pages#portfolio"

  resources :quotes

    resources :customers do
      collection do
          get :search
      end
    end

    resources :buildings do
      collection do
          get :search
      end
    end

    resources :batteries do
      collection do
          get :search
      end
    end

    resources :columns do
      collection do
          get :search
      end
    end


    resources :elevators do
      collection do
          get :search
      end
    end

    resources :employee do
      collection do
          get :search
      end
    end
  
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RocketElevatorsInformationSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
    <meta charset="utf-8" />
    <meta name="description" content="" />
    <!-- mobile settings -->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
    <script>
        var plugin_path = 'assets/plugins/';
    </script>

    <%= favicon_link_tag 'favicon.ico' %>
    
    <script>
        var plugin_path = 'assets/plugins/';
    </script>


  </head>


  
  <body class="smoothscroll enable-animation">
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<% if user_signed_in? && current_user.is_admin != true %>
  Signed in as <%= current_user.email %>. Not you?
  <%= link_to "Edit profile", edit_user_registration_path %>
<% elsif user_signed_in? && current_user.is_admin == true %>
  Signed in as <%= current_user.email %>. Not you?
  <%= link_to "Edit profile", edit_user_registration_path %>
<% end %>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, id: "flash_#{name}" %>
<% end %>
    <div id="header" class="navbar-toggleable-md sticky header-md clearfix">

        <!-- TOP NAV -->
        <header id="topNav">
            <div class="container">

                <!-- Mobile Menu Button -->
                <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
                        <i class="fa fa-bars"></i>
                    </button>

                <!-- Logo -->
                <a class="logo float-left scrollTo">
                    <%= image_tag "R2.png" %>
                </a>

                <!-- 
                        Top Nav 
                        
                        AVAILABLE CLASSES:
                        submenu-dark = dark sub menu
                    -->
                <div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
                    <nav class="nav-main">

                        <!-- 
                                .nav-onepage
                                Required for onepage navigation links
                                
                                Add .external for an external link!
                            -->
                        <ul id="topMain" class="nav nav-pills nav-main nav-onepage">
                            <li class="active">
                                <!-- HOME -->
                                <%= link_to "HOME", root_path, 'data-turbolinks': false %>
                            </li>
                            <li class="dropdown">
                                <!-- services -->
                                <a class="dropdown-toggle" href="#">
                                        SERVICES
                                    </a>
                                <ul class="dropdown-menu">
                                    <li><%= link_to "Residential", residential_path, 'data-turbolinks': false %></li>
                                    <li><%= link_to "Commercial", commercial_path, 'data-turbolinks': false %></li>
                                </ul>
                            </li>
                                <!-- PORTFOLIO-->
                            <li>
                            <%= link_to "PORTFOLIO", "#{root_path}#portfolio", 'data-turbolinks': false %>
                            </li>
                            <li>
                                <!-- NEWS -->
                                <%= link_to "NEWS", "#{root_path}#news", 'data-turbolinks': false %>
                            </li>

                            <li>
                                <!-- CLIENTS -->
                                <%= link_to "CLIENTS", "#{root_path}#clients", 'data-turbolinks': false %>
                            </li>
                            <li>
                                <!-- CONTACT -->
                                <%= link_to "CONTACT", "#{root_path}#contact", 'data-turbolinks': false %>
                            </li>
                            <li>
                                <!-- INTERVENTION -->
                                <% if user_signed_in? && current_user.is_admin == true %>
                                <%= link_to "INTERVENTION", interventions_path %>
                                <% end %>
                            </li>
                                <li>
                                    <!-- LOGIN -->
                                    <%# <a href="/users/sign_in"></a> %>
                                    <% if user_signed_in?  == false %>
                                        <%= link_to "LOG IN", new_user_session_path %>
                                    <% elsif user_signed_in? && current_user.is_admin == true %>
                                        <%= link_to "SIGN OUT", destroy_user_session_path, method: :delete %>
                                    <% end %>
                                </li>
                                    <li>
                                        <% if user_signed_in? && current_user.is_admin != true %>
                                            <%= link_to "SIGN OUT", destroy_user_session_path, method: :delete %>
                                    </li>   
                                    <li>
                                            <% elsif user_signed_in? && current_user.is_admin == true %>
                                            <%= link_to "ADMIN", rails_admin_path %>
                                        <% end %>
                                    </li>
                            
                                
                        </ul>

                    </nav>
                </div>

            </div>
        </header>
        <!-- /Top Nav -->

    </div>

    <%= yield %>
    
    <footer id="footer">
        <div class="container">


            <div class="row">

                <!-- col #1 -->
                <div class="col-md-8">

                    <h3 class="letter-spacing-1">WHY US?</h3>

                    <!-- Small Description -->
                    <p>
                        Rocket Elevators is the leading manufacturer of elevator systems. The developments made by Muxx allowed the construction of skyscrapers equipped with safe elevator systems. Muxx has installed elevators in several of the most famous buildings such as the
                        Eiffel Tower, the Empire State Building, the World Trade Center, The Twilight Zone Tower of Terror, The Petronas Twin Towers, and the Burj Khalifa. In the commercial sphere in Spain, Muxx has worked for the main hotel chains.<br/>                            We have the conviction that we create the most innovative and reliable products on the market. Contact us today for any questions you might have.

                    </p>
                    <h2>(418) 555-1234</h2>
                </div>
                <!-- /col #1 -->

                <!-- col #2 -->
                <div class="col-md-4">
                    <h3 class="letter-spacing-1">KEEP IN TOUCH</h3>

                    <!-- Newsletter Form -->
                    <p>Subscribe to Our Newsletter to get Important News & Offers</p>

                    <form class="validate" action="php/newsletter.php" method="post" data-success="Subscribed! Thank you!" data-toastr-position="bottom-right">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                            <input type="email" id="email" name="email" class="form-control required" placeholder="Enter your Email">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="submit">Subscribe</button>
                            </span>
                        </div>
                    </form>
                    <!-- /Newsletter Form -->


                </div>
                <!-- /col #2 -->

            </div>


        </div>

        <div class="copyright">
            <div class="container">
                <ul class="float-right m-0 list-inline mobile-block">
                    <li><a>Terms &amp; Conditions</a></li>
                    <li>&bull;</li>
                    <li><a>Privacy</a></li>

                </ul>
                &copy; All Rights Reserved, Rocket Elevators Inc
            </div>
        </div>

    </footer>


  </body>
</html>